# essm app teena 
spring.application.name=cabinet-medical

# Connexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cabinet_medical?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=AZERTY123/°
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway (migrations Mta3 base de donnes automatiques)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Thymeleaf
spring.thymeleaf.cache=false

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect